# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: a2a_s13.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'a2a_s13.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ra2a_s13.proto\x12\tlf.a2a.v1\x1a\x1cgoogle/protobuf/struct.proto2\x96\x02\n\nA2AService\x12?\n\x0bSendMessage\x12\x17.google.protobuf.Struct\x1a\x17.google.protobuf.Struct\x12J\n\x14SendStreamingMessage\x12\x17.google.protobuf.Struct\x1a\x17.google.protobuf.Struct0\x01\x12;\n\x07GetTask\x12\x17.google.protobuf.Struct\x1a\x17.google.protobuf.Struct\x12>\n\nCancelTask\x12\x17.google.protobuf.Struct\x1a\x17.google.protobuf.Structb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'a2a_s13_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_A2ASERVICE']._serialized_start=59
  _globals['_A2ASERVICE']._serialized_end=337
# @@protoc_insertion_point(module_scope)
